### ISSUE TITLE
Host tree parsing problems

### ISSUE THREAD

**Issue by ryneches** [arvestad/jprime#27]
I'd like to simulate some gene trees with GuestTreeGen. It seems to work fine for host trees I make with HostTreeGen, but if I try to load real trees, I get weird errors.

```
$ java -jar jprime.jar GuestTreeGen fish.tree 0.01 0.005 0.1 fish

java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
        at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
        at java.base/java.util.LinkedList.remove(LinkedList.java:529)
        at se.cbb.jprime.topology.RBTreeEpochDiscretiser.update(RBTreeEpochDiscretiser.java:188)
        at se.cbb.jprime.topology.RBTreeEpochDiscretiser.<init>(RBTreeEpochDiscretiser.java:100)
        at se.cbb.jprime.apps.genphylodata.GuestTreeInHostTreeCreator.<init>(GuestTreeInHostTreeCreator.java:69)
        at se.cbb.jprime.apps.genphylodata.GuestTreeGenParameters.getHostTreeCreator(GuestTreeGenParameters.java:129)
        at se.cbb.jprime.apps.genphylodata.GuestTreeGen.main(GuestTreeGen.java:79)
        at se.cbb.jprime.apps.JPrIMEStarter.main(JPrIMEStarter.java:116)
```
I don't see anything wrong or weird about my tree. It looks like maybe it's somehow only finding half of the taxa, perhaps? 

[fish.tree.txt](https://github.com/arvestad/jprime/files/1956962/fish.tree.txt)

**Comment by arvestad** [comment]
It must have something to do with the tree not being ultrametric, and perhaps some of the short branches are playing in? It is actually supposed to be an ultrametric host tree (we did not foresee your application), but I have noted that some non-ultrametric trees still work as host trees.

Would it be possible to find "proper" datings of the branches in your input tree?

Still, I am looking into possible fixes.

**Comment by arvestad** [comment]
To be clear: this is not a parsing problem.

**Comment by ryneches** [comment]
> To be clear: this is not a parsing problem.

Ah! Well, that explains why I wasn't able to figure out how to fix it. :-)

I also got it to work for a few non-ultrametric trees, and so I'd forgotten that `--help` specifies ultrametric trees. It's not ideal, but I can make approximate an ultrametric tree.

**Comment by arvestad** [comment]
OK, let me know how it goes!
